// Generated by `mcp__supabase__generate_typescript_types`. Re-run when the schema changes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      announcements: {
        Row: {
          id: number;
          slug: string;
          title: string;
          body: string;
          published_at: string | null;
          posted_by: string | null;
          pinned: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          slug: string;
          title: string;
          body: string;
          published_at?: string | null;
          posted_by?: string | null;
          pinned?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          slug?: string;
          title?: string;
          body?: string;
          published_at?: string | null;
          posted_by?: string | null;
          pinned?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      historical_player_stats: {
        Row: {
          assists: number;
          conference: string;
          created_at: string;
          deleted: number;
          demos: number;
          goals: number;
          id: number;
          player_name: string;
          saves: number;
          season: number;
        };
        Insert: {
          assists?: number;
          conference: string;
          created_at?: string;
          deleted?: number;
          demos?: number;
          goals?: number;
          id?: number;
          player_name: string;
          saves?: number;
          season: number;
        };
        Update: {
          assists?: number;
          conference?: string;
          created_at?: string;
          deleted?: number;
          demos?: number;
          goals?: number;
          id?: number;
          player_name?: string;
          saves?: number;
          season?: number;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          admin_pitch: string | null;
          captain_pitch: string | null;
          created_at: string;
          discord_avatar_url: string | null;
          discord_global_name: string | null;
          discord_id: string | null;
          discord_username: string | null;
          id: string;
          in_player_pool: boolean;
          is_admin: boolean;
          is_admin_applicant: boolean;
          is_captain: boolean;
          is_captain_applicant: boolean;
          peak_rank: string | null;
          peak_rank_playlist: string | null;
          rank_2v2: string | null;
          rank_3v3: string | null;
          ranks_updated_at: string | null;
          rl_tracker_url: string | null;
          updated_at: string;
        };
        Insert: {
          admin_pitch?: string | null;
          captain_pitch?: string | null;
          created_at?: string;
          discord_avatar_url?: string | null;
          discord_global_name?: string | null;
          discord_id?: string | null;
          discord_username?: string | null;
          id: string;
          in_player_pool?: boolean;
          is_admin?: boolean;
          is_admin_applicant?: boolean;
          is_captain?: boolean;
          is_captain_applicant?: boolean;
          peak_rank?: string | null;
          peak_rank_playlist?: string | null;
          rank_2v2?: string | null;
          rank_3v3?: string | null;
          ranks_updated_at?: string | null;
          rl_tracker_url?: string | null;
          updated_at?: string;
        };
        Update: {
          admin_pitch?: string | null;
          captain_pitch?: string | null;
          created_at?: string;
          discord_avatar_url?: string | null;
          discord_global_name?: string | null;
          discord_id?: string | null;
          discord_username?: string | null;
          id?: string;
          in_player_pool?: boolean;
          is_admin?: boolean;
          is_admin_applicant?: boolean;
          is_captain?: boolean;
          is_captain_applicant?: boolean;
          peak_rank?: string | null;
          peak_rank_playlist?: string | null;
          rank_2v2?: string | null;
          rank_3v3?: string | null;
          ranks_updated_at?: string | null;
          rl_tracker_url?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type TablesInsert<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];

export type Profile = Tables<"profiles">;
export type HistoricalPlayerStatsRow = Tables<"historical_player_stats">;
export type Announcement = Tables<"announcements">;
